#! /usr/bin/env python3

import csv
import sys
from pathlib import Path
import re

from tomllib import loads


def strip_braces(s: str):
    if s.startswith("{") and s.endswith("}"):
        return s[1:-1]
    else:
        return s


HYPERLINK_RE = re.compile(r"\\hyperlink\s*\{(.*?)\}\{(.*?)\}")


def strip_hyperlink(s: str):
    match = HYPERLINK_RE.match(s)
    if not match:
        return s
    return match.group(2)


def main():
    toml_txt = (
        Path("out/notes-content.toml")
        .read_text()
        .replace("\\", "\\\\")
        )

    data = loads(toml_txt)["content"]

    outf = csv.writer(sys.stdout)
    outf.writerow([
            "Identifier",
            "Start",
            "End",
            "Section",
            "Frame Title",
            "Section Title",
            "Subsection Title"])

    for i, row in enumerate(data):
        outf.writerow([
                row["identifier"],
                row["start"],
                data[i+1]["start"] if i+1 < len(data) else row["start"],
                row["section"],
                strip_braces(row["frame_title"]),
                strip_hyperlink(row["section_title"]),
                strip_hyperlink(row["subsection_title"])])


if __name__ == "__main__":
    main()
